In [142]:
import  numpy as np
import  pandas as pd
import warnings
warnings.filterwarnings('ignore')

# Importing data

In [143]:
train = pd.read_csv('D:/AI-Course/Py.Prac/archive/train_u6lujuX_CVtuZ9i.csv')
test = pd.read_csv('D:/AI-Course/Py.Prac/archive/test_Y3wMUE5_7gLdaTN.csv')

# Data Cleaning

In [144]:
train

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [145]:
train.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [146]:
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [147]:
test

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [148]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [149]:
test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

**Approval of loans between Males & Females**

In [150]:
pd.crosstab(train.Gender, train.Loan_Status, margins = True)

Loan_Status    N    Y  All
Gender                    
Female        37   75  112
Male         150  339  489
All          187  414  601

**Filling up NAN values of Gender and Converting categorial variables(Female,Male) to numerical variables(0,1)**

In [151]:
train.Gender = train.Gender.fillna(train.Gender.mode())
test.Gender = test.Gender.fillna(test.Gender.mode())

In [152]:
sex = pd.get_dummies(train['Gender'] , drop_first = True )

In [153]:
train.drop(['Gender'], axis = 1 , inplace =True)
train = pd.concat([train , sex ] , axis = 1)

In [154]:
sex = pd.get_dummies(test['Gender'] , drop_first = True )

In [155]:
test.drop(['Gender'], axis = 1 , inplace =True)
test = pd.concat([test , sex ] , axis = 1)

In [156]:
train.rename(columns = {'Male':'gender'}, inplace = True)

In [157]:
test.rename(columns = {'Male':'gender'}, inplace = True)

**Approval of loans between different sizes of families**

In [158]:
pd.crosstab(train.Dependents , train.Loan_Status, margins = True)

Loan_Status    N    Y  All
Dependents                
0            107  238  345
1             36   66  102
2             25   76  101
3+            18   33   51
All          186  413  599

**Filling up NAN values of Dependents and Converting categorial variables(1,2,3+) to numerical variables(1,2,3)**

In [159]:
train.Dependents.unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [160]:
train.Dependents = train.Dependents.fillna("0")
test.Dependents = test.Dependents.fillna("0")

rplc = {'0':'0', '1':'1', '2':'2', '3+':'3'}

train.Dependents = train.Dependents.replace(rplc).astype(int)
test.Dependents = test.Dependents.replace(rplc).astype(int)

**Approval of loans people those who have Credit History and those who don't**

In [161]:
pd.crosstab(train.Credit_History , train.Loan_Status, margins = True)

Loan_Status       N    Y  All
Credit_History               
0.0              82    7   89
1.0              97  378  475
All             179  385  564

**Filling up NAN values of Credit history by taking the mode**

In [162]:
train.Credit_History = train.Credit_History.fillna(train.Credit_History.mode()[0])
test.Credit_History  = test.Credit_History.fillna(test.Credit_History.mode()[0])

**Approval of loans between people who are Self-employed & who aren't**

In [163]:
pd.crosstab(train.Self_Employed , train.Loan_Status,margins = True)

Loan_Status      N    Y  All
Self_Employed               
No             157  343  500
Yes             26   56   82
All            183  399  582

**Approval of loans between people who are Self-employed & who aren't**

In [164]:
train.Self_Employed = train.Self_Employed.fillna(train.Self_Employed.mode())
test.Self_Employed = test.Self_Employed.fillna(test.Self_Employed.mode())

self_Employed = pd.get_dummies(train['Self_Employed'] ,prefix = 'employed' ,drop_first = True )
train.drop(['Self_Employed'], axis = 1 , inplace =True)
train = pd.concat([train , self_Employed ] , axis = 1)


In [165]:
self_Employed = pd.get_dummies(test['Self_Employed'] , prefix = 'employed' ,drop_first = True )
test.drop(['Self_Employed'], axis = 1 , inplace =True)
test = pd.concat([test , self_Employed ] , axis = 1)

**Approval of loans between Married and Unmarried people**

In [166]:
pd.crosstab(train.Married , train.Loan_Status,margins = True)

Loan_Status    N    Y  All
Married                   
No            79  134  213
Yes          113  285  398
All          192  419  611

**Filling NAN values and Converting categorial variables(Yes,No) to numerical variables(1,0)**

In [167]:
train.Married = train.Married.fillna(train.Married.mode())
test.Married = test.Married.fillna(test.Married.mode())

married = pd.get_dummies(train['Married'] , prefix = 'married',drop_first = True )
train.drop(['Married'], axis = 1 , inplace =True)
train = pd.concat([train , married ] , axis = 1)

married = pd.get_dummies(test['Married'] , prefix = 'married', drop_first = True )
test.drop(['Married'], axis = 1 , inplace =True)
test = pd.concat([test , married ] , axis = 1)

**Filling up NAN values of Loan Amount Term**

In [168]:
train.drop(['Loan_Amount_Term'], axis = 1 , inplace =True)
test.drop(['Loan_Amount_Term'], axis = 1 , inplace =True)

train.LoanAmount = train.LoanAmount.fillna(train.LoanAmount.mean()).astype(int)
test.LoanAmount = test.LoanAmount.fillna(test.LoanAmount.mean()).astype(int)

**Converting categorial variables to numerical variables**

In [169]:
train.Education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [170]:
test.Education.unique()

array(['Graduate', 'Not Graduate'], dtype=object)

In [171]:
train['Education'] = train['Education'].map( {'Graduate': 0, 'Not Graduate': 1} ).astype(int)
test['Education'] = test['Education'].map( {'Graduate': 0, 'Not Graduate': 1} ).astype(int)

In [172]:
train.Property_Area.unique()

array(['Urban', 'Rural', 'Semiurban'], dtype=object)

In [173]:
test.Property_Area.unique()

array(['Urban', 'Semiurban', 'Rural'], dtype=object)

In [174]:
train['Property_Area'] = train['Property_Area'].map( {'Urban': 0, 'Semiurban': 1 ,'Rural': 2  } ).astype(int)

test.Property_Area = test.Property_Area.fillna(test.Property_Area.mode())
test['Property_Area'] = test['Property_Area'].map( {'Urban': 0, 'Semiurban': 1 ,'Rural': 2  } ).astype(int)

In [175]:
train.Loan_Status.unique()

array(['Y', 'N'], dtype=object)

In [176]:
train['Loan_Status'] = train['Loan_Status'].map( {'N': 0, 'Y': 1 } ).astype(int)

In [177]:
train.drop(['Loan_ID'], axis = 1 , inplace =True)

In [178]:
X = train.drop('Loan_Status' , axis = 1 )
y = train['Loan_Status']

# ML Models Creating

## Split data

In [179]:
from sklearn.model_selection import train_test_split

In [180]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((491, 10), (123, 10), (491,), (123,))

## LinearRegression

In [181]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [182]:
model.fit(X,y)

LinearRegression()

In [183]:
print("Training score:",model.score(X_train,y_train))
print("Testing score:",model.score(X_test,y_test))

Training score: 0.31372218515198924
Testing score: 0.2893978614548428


In [184]:
model.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]]) 

array([0.88067143])

In [185]:
model.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0.68823417])

## Logistic Regression

In [186]:
from sklearn.linear_model import LogisticRegression
model1 = LogisticRegression()

In [187]:
model1.fit(X_train, y_train)

LogisticRegression()

In [188]:
print("Training score:",model1.score(X_train,y_train))
print("Testing score:",model1.score(X_test,y_test))

Training score: 0.8228105906313645
Testing score: 0.7886178861788617


In [189]:
model1.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]]) 

array([1])

In [190]:
model1.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([1])

## Random Forest Algorithm

In [191]:
from sklearn.ensemble import RandomForestRegressor
RF=RandomForestRegressor(n_estimators=100)

In [192]:
RF.fit(X_train,y_train)

RandomForestRegressor()

In [193]:
print("Training Score:",RF.score(X_train,y_train))
print("Testing Score:",RF.score(X_test,y_test))

Training Score: 0.8918129224066879
Testing Score: 0.189565872093023


In [194]:
RF.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([0.58])

In [195]:
RF.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0.44])

## SVC Algorithm

In [200]:
from sklearn.svm import SVC
SV = SVC(C=15,kernel="rbf")

In [201]:
SV.fit(X_train, y_train)

SVC(C=15)

In [202]:
print("Training score:",SV.score(X_train,y_train))
print("Testing score:",SV.score(X_test,y_test))

Training score: 0.7107942973523421
Testing score: 0.6422764227642277


In [203]:
SV.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([1])

In [204]:
SV.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0])

## Gradient Boosting Algorithm

In [205]:
from sklearn.ensemble import GradientBoostingRegressor

In [206]:
GB=GradientBoostingRegressor()
GB.fit(X_train,y_train)

GradientBoostingRegressor()

In [207]:
print("Training score:",GB.score(X_train,y_train))
print("Testing score:",GB.score(X_test,y_test))

Training score: 0.6485958813561308
Testing score: 0.19507008684625804


In [208]:
GB.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([0.62705919])

In [209]:
GB.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0.39115809])

## Extreme Gradient Boosting

In [210]:
import xgboost
from xgboost import XGBRegressor

In [211]:
XGB=XGBRegressor()
XGB.fit(X_train,y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [212]:
print("Training test:",XGB.score(X_train,y_train))
print("Testing Test:",XGB.score(X_test,y_test))

Training test: 0.9981697255447913
Testing Test: 0.05699997990675065


## Naive Bayes

In [213]:
from sklearn.naive_bayes import GaussianNB

In [214]:
GNB = GaussianNB()
GNB.fit(X_train, y_train)

GaussianNB()

In [215]:
print("Training test:",GNB.score(X_train,y_train))
print("Testing Test:",GNB.score(X_test,y_test))

Training test: 0.8004073319755601
Testing Test: 0.7886178861788617


In [216]:
GNB.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([1])

In [217]:
GNB.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0])

## K-Nearest Neighbors

In [218]:
from sklearn.neighbors import KNeighborsClassifier

In [219]:
KN= KNeighborsClassifier(n_neighbors = 3)
KN.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [220]:
print("Training test:",KN.score(X_train,y_train))
print("Testing Test:",KN.score(X_test,y_test))

Training test: 0.7718940936863544
Testing Test: 0.6341463414634146


In [221]:
KN.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([1])

In [222]:
KN.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([0])

## Decision Tree

In [231]:
from sklearn.tree import DecisionTreeClassifier
DT=DecisionTreeClassifier()
DT.fit(X_train,y_train)

DecisionTreeClassifier()

In [232]:
print("Training score:",DT.score(X_train,y_train))
print("Testing score:",DT.score(X_test,y_test))

Training score: 1.0
Testing score: 0.6422764227642277


In [233]:
DT.predict([[0,0,3000,0.0,66,1.0,0,1,1,1]])

array([0])

In [234]:
DT.predict([[1,0,4583,15080.0,128,1.0,2,1,0,1]])

array([1])